-- AlterTable
ALTER TABLE "Flashcard" ADD COLUMN     "acertos" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "intervalo" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "proxRevisao" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
